image:
  repository: tccr.io/truecharts/gonic
  pullPolicy: IfNotPresent
  tag: v0.16.0@sha256:c19ed2aadbfe300d4978dc0ca9d96998b4d66ecdccc80f05327211dfafa4a540
# env:
#   GONIC_MUSIC_PATH:
#   GONIC_PODCAST_PATH:
#   GONIC_CACHE_PATH:
service:
  main:
    ports:
      main:
        port: 10023
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
